# Generated by Django 4.0.2 on 2022-02-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='year_in_school',
            new_name='role',
        ),
    ]
