# Generated by Django 4.0.2 on 2022-02-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='ALLOW_SUNDAY',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='SATURDAY_END',
            field=models.TimeField(default='12:00', null=True),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='SATURDAY_START',
            field=models.TimeField(default='09:00', null=True),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='WEEKDAYS_END',
            field=models.TimeField(default='17:00', null=True),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='WEEKDAYS_START',
            field=models.TimeField(default='09:00', null=True),
        ),
    ]
