# Generated by Django 4.0.2 on 2022-03-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_alter_appsettings_allow_sunday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='IS_OPEN',
            field=models.BooleanField(default=True),
        ),
    ]
